// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dywvplgvhjvgpdyjxaud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5d3ZwbGd2aGp2Z3BkeWp4YXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDExODMsImV4cCI6MjA2NTU3NzE4M30.yUvhxMNPcz-aexgTbRIu4NetJiu-FleeMVfBRUOgd30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});